FROM ubuntu:16.04

LABEL maintainer="Cedric Gerber <gerber.cedric@gmail.com>"


RUN dpkg --add-architecture i386 && apt-get update && apt-get install -y \
  libc6:i386                    \
  libx11-6:i386                 \
  libasound2:i386               \
  libatk1.0-0:i386              \
  libcairo2:i386                \
  libcups2:i386                 \
  libdbus-glib-1-2:i386         \
  libgconf-2-4:i386             \
  libgcrypt20:i386              \
  libgdk-pixbuf2.0-0:i386       \
  libgtk-3-0:i386               \
  libice6:i386                  \
  libncurses5:i386              \
  libsm6:i386                   \
  liborbit2:i386                \
  libudev1:i386                 \
  libusb-0.1-4:i386             \
  libstdc++6:i386               \
  libstdc++6					          \
  libxt6						            \
  libxt6:i386                   \
  libxtst6:i386                 \
  libgnomeui-0:i386             \
  libusb-1.0-0-dev:i386         \
  libcanberra-gtk-module:i386   \
  gtk2-engines-murrine:i386     \
  libpython2.7				          \
  unzip         				        \
  wget

# Install missing library
WORKDIR /ccs_install
RUN wget https://launchpad.net/ubuntu/+archive/primary/+files/libgcrypt11_1.5.3-2ubuntu4.2_amd64.deb && dpkg -i libgcrypt11_1.5.3-2ubuntu4.2_amd64.deb

COPY libudev0_175-0ubuntu19_i386.deb /ccs_install/libudev0_175-0ubuntu19_i386.deb
RUN dpkg -i /ccs_install/libudev0_175-0ubuntu19_i386.deb

RUN export JAVA_TOOL_OPTIONS=-Xss1280k

RUN mkdir /etc/udev/rules.d

COPY response_custom.txt /ccs_install

ADD CCS7.3.0.00019_linux-x64.tar.gz /ccs_install

RUN /ccs_install/CCS7.3.0.00019_linux-x64/ccs_setup_linux64_7.3.0.00019.bin --mode unattended --prefix /opt/ti --response-file /ccs_install/response_custom.txt 	

RUN rm -r /ccs_install

ENV PATH="/opt/ti/ccsv7/eclipse:${PATH}"

RUN mkdir /workspace

VOLUME /workdir
WORKDIR /workdir

COPY /msp430 /msp430

RUN /opt/ti/ccsv7/eclipse/eclipse -noSplash -data "/workspace" -application com.ti.ccstudio.apps.projectImport -ccs.location /msp430/ -ccs.copyIntoWorkspace